<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>7aaa0dc9-5151-4fab-99a2-86b8baa5c82d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.popover-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59cd58fe-ca45-4ca5-b767-414ecb0af016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://vc.ru/?writing=0</value>
      <webElementGuid>504b6fe1-044c-420d-9557-c20a19e9bfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dbf8caf6-e6eb-4267-90cd-1ec5c2d7261c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-item</value>
      <webElementGuid>b4e5a94d-2486-43cf-9ec9-9b999c59c6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   
                  Запись
                  </value>
      <webElementGuid>6dc0ee27-e083-4966-a563-c6491dfa9db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app app--content-feed app--left-column-on app--right-column-on app--propaganda-on app--livestream-on app--content-sidebar-align-right app--right-column-reserve-off app--live-auto app--ad-allowed os--non_ios&quot;]/div[@class=&quot;site-header-container&quot;]/div[@class=&quot;site-header site-header--vc&quot;]/div[@class=&quot;site-header__section site-header__section--create&quot;]/div[@class=&quot;navigation-create&quot;]/div[@class=&quot;popover&quot;]/div[@class=&quot;popover__main vb vb-invisible&quot;]/div[@class=&quot;popover__scrollable vb-content&quot;]/div[@class=&quot;popover__content&quot;]/div[@class=&quot;popover__section&quot;]/div[@class=&quot;popover__list&quot;]/a[@class=&quot;popover-item&quot;]</value>
      <webElementGuid>4de10597-290f-4770-94a1-dadcf570a418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://vc.ru/?writing=0')]</value>
      <webElementGuid>be9e298c-af22-4afb-b848-d5511bedb730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>87df7ca5-3ba1-42fa-91ba-00de8c9bff5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://vc.ru/?writing=0' and (text() = '   
                  Запись
                  ' or . = '   
                  Запись
                  ')]</value>
      <webElementGuid>a363e8fa-406e-479b-a337-bd3e245751d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
