<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>f3cf7517-7078-42f9-80d9-b08c70b27f65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.v-button.v-button--default.v-button--size-default.auth-social__button.auth-social__button--email.auth-social__button--with-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>070f2dc2-fac1-444e-b8d1-1a10a47e7099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-layout-mobile</name>
      <type>Main</type>
      <value>icon,label</value>
      <webElementGuid>b0f1a62c-6d41-46c2-8db0-2716dc1ba94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-layout-desktop</name>
      <type>Main</type>
      <value>icon,label</value>
      <webElementGuid>24679e4c-2579-4245-9906-e43219ad6a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-button v-button--default v-button--size-default auth-social__button auth-social__button--email auth-social__button--with-label</value>
      <webElementGuid>ed627ffb-349b-40fa-a492-15f2ba70a4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm</name>
      <type>Main</type>
      <value>Login — Mail — Click</value>
      <webElementGuid>d7383fb1-0ef1-4f2a-8a1c-53a87063a3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-social</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>59d95bfb-9995-411a-a5ae-0ac4b823b4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
        Почта
       </value>
      <webElementGuid>d19dd93d-eab3-4eb6-94f4-ff2cf878e7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app app--content-feed app--left-column-on app--right-column-on app--propaganda-on app--livestream-on app--content-sidebar-align-right app--right-column-reserve-off app--live-auto app--ad-allowed os--non_ios&quot;]/div[@class=&quot;v-popup-container&quot;]/div[@class=&quot;v-popup-overlay v-popup-overlay--center v-popup-overlay__mobile-fullscreen&quot;]/div[@class=&quot;v-popup-window v-popup-window--center v-popup-window--white v-popup-window--mobile-fullscreen v-popup-window--with-cover&quot;]/div[@class=&quot;v-popup-window__content&quot;]/div[@class=&quot;auth&quot;]/div[@class=&quot;auth-social auth__view v-form&quot;]/div[@class=&quot;v-form__content&quot;]/div[@class=&quot;auth-social__container&quot;]/button[@class=&quot;v-button v-button--default v-button--size-default auth-social__button auth-social__button--email auth-social__button--with-label&quot;]</value>
      <webElementGuid>a9ddf55d-5e9b-414f-ba8e-603e848d51e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/button[2]</value>
      <webElementGuid>281d779a-1892-42ce-a995-fc4a59b08af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' 
        Почта
       ' or . = ' 
        Почта
       ')]</value>
      <webElementGuid>4aaa696a-a42e-4d03-a736-c561ec2818a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
