<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>2ff6ca60-cd2d-41a9-8a13-310a062bcc5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.v-button.v-button--default.v-button--size-default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97e76b5a-9e74-47e0-aafe-f90f7bc88667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-layout-mobile</name>
      <type>Main</type>
      <value>icon,label</value>
      <webElementGuid>7e32281c-6c24-4232-b610-dc21084921ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-layout-desktop</name>
      <type>Main</type>
      <value>icon,label</value>
      <webElementGuid>3a45213a-a50d-451c-93c7-1952eea85f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-button v-button--default v-button--size-default</value>
      <webElementGuid>62bc2a8b-4e59-4ecd-abe2-e634b00a968b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
    Создать
  </value>
      <webElementGuid>a82bf3c7-f313-4379-b061-f2bb9ada655d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app app--content-feed app--left-column-on app--right-column-on app--propaganda-on app--livestream-on app--content-sidebar-align-right app--right-column-reserve-off app--live-auto app--ad-allowed os--non_ios&quot;]/div[@class=&quot;site-header-container&quot;]/div[@class=&quot;site-header site-header--vc&quot;]/div[@class=&quot;site-header__section site-header__section--create&quot;]/div[@class=&quot;navigation-create&quot;]/button[@class=&quot;v-button v-button--default v-button--size-default&quot;]</value>
      <webElementGuid>6a9b4445-c60f-4dc4-81dc-ef8e9a819adc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>da769a1c-3d6e-4aa3-a063-b4301788ae60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' 
    Создать
  ' or . = ' 
    Создать
  ')]</value>
      <webElementGuid>ec76cbd9-e517-42be-90c9-c2cf42272c63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
