<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>c14c6261-cc74-404f-9a4c-eab322380279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>530992cb-eede-4eb5-9420-eb35307f8c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b7280a96-589a-410e-b01a-15021325db1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>П​а​р​о​л​ь​</value>
      <webElementGuid>1e7514a5-ae9c-47fa-9e1f-0904f3b1f20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b58a12cd-92dd-4b12-8e21-356dd9389f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>9ba29e42-119a-4e8e-a31d-91f0012b5c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c5876f8e-0cc6-4d5f-8dd9-35159738e571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-text-input__input</value>
      <webElementGuid>807bb14e-49c4-4de1-b50a-0995a866bff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app app--content-feed app--left-column-on app--right-column-on app--propaganda-on app--livestream-on app--content-sidebar-align-right app--right-column-reserve-off app--live-auto app--ad-allowed os--non_ios&quot;]/div[@class=&quot;v-popup-container&quot;]/div[@class=&quot;v-popup-overlay v-popup-overlay--center v-popup-overlay__mobile-fullscreen&quot;]/div[@class=&quot;v-popup-window v-popup-window--center v-popup-window--white v-popup-window--mobile-fullscreen v-popup-window--with-cover&quot;]/div[@class=&quot;v-popup-window__content&quot;]/div[@class=&quot;auth&quot;]/div[@class=&quot;auth-form auth__view v-form auth-form--email-login&quot;]/div[@class=&quot;v-form__content&quot;]/div[@class=&quot;v-field--text form-item v-field v-field--default&quot;]/div[@class=&quot;v-field__wrapper&quot;]/label[@class=&quot;v-text-input v-text-input--default&quot;]/input[@class=&quot;v-text-input__input&quot;]</value>
      <webElementGuid>e84c3550-48e7-43f6-a9f0-e74763f43899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>64f0d7b7-e1b2-4a73-be39-41b5f1348119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>f401d3d6-c003-44f2-8519-f3a834800ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'П​а​р​о​л​ь​' and @name = 'password']</value>
      <webElementGuid>12f156c7-5bfd-4c8c-a722-7ed11bc1ccc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
