<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_writing-title</name>
   <tag></tag>
   <elementGuidId>8e9a4318-dc34-4f4b-a40f-cb4821d008b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.writing-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d31cb8d8-840a-4e53-b6bb-33d497b303bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fc356cfa-0ee8-482f-bdca-a11d66a87b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Заголовок</value>
      <webElementGuid>ad8cf1b3-3e10-44ca-b6d2-92e23ef1e1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>default</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>fe9a3e41-1c88-4fe6-9d9d-79ce4f31126e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>4e74e4c7-133b-4daf-ae04-7d4c68177c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>writing-title</value>
      <webElementGuid>9cedd673-4e6b-487a-857b-87f69b1087b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e977d75-d5b6-4571-9463-b7b4836cecde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app app--content-feed app--left-column-on app--right-column-on app--propaganda-on app--livestream-on app--content-sidebar-align-right app--right-column-reserve-off app--live-auto app--ad-allowed os--non_ios&quot;]/div[@class=&quot;main layout&quot;]/div[@class=&quot;layout__content l-relative&quot;]/div[@class=&quot;v-popup-fp-container&quot;]/div[@class=&quot;v-popup-fp-overlay&quot;]/div[@class=&quot;v-popup-fp-window&quot;]/div[@class=&quot;v-popup-fp-window__body&quot;]/div[@class=&quot;writing l-island-bg&quot;]/div[@class=&quot;writing__body&quot;]/div[@class=&quot;writing__scrollable&quot;]/div[@class=&quot;writing__content&quot;]/div[@class=&quot;l-editor&quot;]/div[@class=&quot;ui-limited-input ui-limited-input--big&quot;]/textarea[@class=&quot;writing-title&quot;]</value>
      <webElementGuid>ef5d625b-232c-4212-8ea0-3e2bb502a734</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2413defd-8620-4ad4-9f14-58c32fd02eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Заголовок']</value>
      <webElementGuid>28f32890-80fb-46bd-9eb8-5c46cf06b310</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
